name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test
      # Optionnel : Verify JaCoCo (décommenter si nécessaire)
      #- name: Verify JaCoCo Coverage
      #  run: mvn verify

      # Optionnel : Analyse SonarQube (décommenter si nécessaire)
      # - name: Run SonarQube Analysis
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: mvn sonar:sonar -Dsonar.projectKey=auto-diagnostic \
      #     -Dsonar.host.url=http://localhost:9000 \
      #     -Dsonar.login=$SONAR_TOKEN

      - name: Build Docker Image
        run: docker build -t auto-diagnostic .

      - name: Run Docker Container
        run: docker run --rm -p 8080:8080 auto-diagnostic
