name: Build and Analyze

on:
  workflow_dispatch: # Ajoute un déclenchement manuel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run JaCoCo and SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=auto-diagnostic \
          -Dsonar.host.url=http://localhost:9000\
          -Dsonar.login=$SONAR_TOKEN
      - name: Verify JaCoCo Coverage
        run: mvn verify